export { default as HomeHero } from "./Home/Hero";
export { default as HomeAbout } from "./Home/About";
export { default as HomeServices } from "./Home/Services";
export { default as CallToAction } from "./CallToAction";
export { default as Numbers } from "./Numbers";
export { default as Testimonials } from "./Home/Testimonials";
export { default as Gallery } from "./Home/Gallery";
export { default as FAQ } from "./Home/FAQ";
export { default as Team } from "./Team";
export { default as CommonHero } from "./CommonHero";
export { Block, BlockReverse } from "./Block";
export { default as Contact } from "./Contact";
